mode: simulation
loggingEnabled: false
simulationOptions:
  videoPort: 44209
  webAPIPort: 44210
  videoQuality: 60
  selectedWaterContainer: waterpool1
  selectedRobot: okon2
  selectedRandomObjects: [gate4, gate2, tripod1, tripod1, obstacle1]
  fixedDeltaTime: 0.001
  depthMapQuality: 90
  depthMapScale: 0.1
  videoFeedQuality: 90
  videoFeedScale: 0.5
  
datasetOptions:
  classNames: [gate, obstacle]
  selectedObjects: [gate4, obstacle1, gate2, tripod1]
  selectedWaterContainer: waterpool1
  objectVisibleFrameNum: 10
  objectMultipleFrameNum: 50
  objectBlankFrameNum: 3
  minCameraDistanceToObject: 0
  maxCameraDistanceToObject: 30
  minObjectFill: 0.01499999989
  minObjectColorPercentVisible: 0.149999997     
  checkFogVisibility: true
  percentClosest: 0.050000006 
  closestMaxDistanceOffset: 2
  objectFillOffset: 0.00999999978
  datasetDirPath: dataset
  overrideDataset: true
  cameraLookAtObjectPitchOffset: 30
  cameraLookAtObjectYawOffset: 30
  cameraLookAtObjectRollOffset: 30
  cameraLookRandomlyPitchOffset: 45
  cameraLookRandomlyRollOffset: 45
  testPointsNum: 1000
  graphicsOptions:
    fogColorRandomized: true
    fogEnabled: true
    randomizeFogDensity: true
    fogDensity: 0.150000006
    fogColor:
    - 0
    - 0.639999986
    - 1
    bloomIntensity: 1.88999999
    mixerRedOutRedIn: 62
    mixerGreenOutGreenIn: 100
    mixerBlueOutBlueIn: 100
    grainIntesity: 0.300000012
    ambientOcclusionIntensity: 0.25999999
    randomizeLightIntesity: true
    lightIntesity: 1
    ambientLightColor:
    - 0
    - 0.639999986
    - 1
    ambientLightIntesity: 0.100000001
    cameraBackgroundColor:
    - 0
    - 0.639999986
    - 1
    cameraFocalLength: 2.55071807
    cameraSensorSize:
    - 4.80000019
    - 3.5999999
  debugOptions:
    drawDetectionRect: true
    drawPostProcessDebug: false
    disableScreenshot: false
    logDetection: true
