mode: simulation
loggingEnabled: true
simulationOptions:
  videoPort: 44209
  webAPIPort: 44210 
  videoQuality: 60
  selectedWaterContainer: level1
  selectedRandomObjects: []
  fixedDeltaTime: 0.05
  depthMapQuality: 100
  depthMapScale: 0.1
  videoFeedQuality: 75
  videoFeedScale: .5
  
datasetOptions:
  classNames: [gate]
  selectedObjects: [gate2]
  selectedWaterContainer: waterpool1
  classDetectedFrameNum: 20
  classMultipleFrameNum: 0 
  classBlankFrameNum: 0
  classObstacleFrameNum: 0
  minVisibleMultipleObjectsNum: 2
  minCameraDistanceToObject: 0
  maxCameraDistanceToObject: 30
  minObjectFill: 0.01
  minObjectColorPercentVisible: 0.149999997     
  checkFogVisibility: true
  percentClosest: 0.050000006 
  closestMaxDistanceOffset: 2
  objectFillOffset: 0.00999999978
  datasetDirPath: dataset
  overrideDataset: true
  cameraLookAtObjectPitchOffset: 30
  cameraLookAtObjectYawOffset: 30
  cameraLookAtObjectRollOffset: 30
  cameraLookRandomlyPitchOffset: 45
  cameraLookRandomlyRollOffset: 45
  testPointsNum: 1000
  graphicsOptions:
    fogColorRandomized: true
    fogEnabled: true
    randomizeFogDensity: true
    fogDensity: 0.150000006
    fogColor:
    - 0
    - 0.639999986
    - 1
    bloomIntensity: 1.88999999
    mixerRedOutRedIn: 62
    mixerGreenOutGreenIn: 100
    mixerBlueOutBlueIn: 100
    grainIntesity: 0.300000012
    ambientOcclusionIntensity: 0.25999999
    randomizeLightIntesity: true
    lightIntesity: 1
    ambientLightColor:
    - 0
    - 0.639999986
    - 1
    ambientLightIntesity: 0.100000001
    cameraBackgroundColor:
    - 0
    - 0.639999986
    - 1
    cameraFocalLength: 2.55071807
    cameraSensorSize:
    - 4.80000019
    - 3.5999999
  debugOptions:
    drawDetectionRect: true
    drawPostProcessDebug: false
    disableScreenshot: false
    logDetection: true
